from typing import List
from pydantic import BaseModel

class DadosEntradaFormatadosModel(BaseModel):
    username: str
    password: str
    footprint: str
    url_cookie: str
    processo: str
    processo_originario: str
    titulo: str
    data_distribuicao: str
    pasta: str
    uf: str
    cidade: str
    orgao_julgador: str
    rito: str
    sistema_tribunal: str
    nome_envolvido: str
    cpf_cnpj_envolvido: str
    qualificacao_envolvido: str
    arquivo_principal: str
    natureza: str
    fase: str
    empresa: str
    qualificacao_empresa: str
    situacao:str
    houve_expedicao: str
    descricao_objeto: str
    portfolio: str
    competencia: str
    nome_responsavel: str
    id_responsavel: str = ''
    situacao_outros_envolvidos1: str
    posicao_outros_envolvidos1: str
    nome_outros_envolvidos1: str
    cpf_cnpj_outros_envolvidos1: str
    situacao_outros_envolvidos2: str
    posicao_outros_envolvidos2: str
    nome_outros_envolvidos2: str
    cpf_cnpj_outros_envolvidos2: str
    situacao_outros_envolvidos3: str
    posicao_outros_envolvidos3: str
    nome_outros_envolvidos3: str
    cpf_cnpj_outros_envolvidos3: str
    situacao_outros_envolvidos4: str
    posicao_outros_envolvidos4: str
    nome_outros_envolvidos4: str
    cpf_cnpj_outros_envolvidos4: str
    situacao_outros_envolvidos5: str
    posicao_outros_envolvidos5: str
    nome_outros_envolvidos5: str
    cpf_cnpj_outros_envolvidos5: str
    situacao_outros_envolvidos6: str
    posicao_outros_envolvidos6: str
    nome_outros_envolvidos6: str
    cpf_cnpj_outros_envolvidos6: str
    situacao_outros_envolvidos7: str
    posicao_outros_envolvidos7: str
    nome_outros_envolvidos7: str
    cpf_cnpj_outros_envolvidos7: str
    situacao_outros_envolvidos8: str
    posicao_outros_envolvidos8: str
    nome_outros_envolvidos8: str
    cpf_cnpj_outros_envolvidos8: str
    situacao_outros_envolvidos9: str
    posicao_outros_envolvidos9: str
    nome_outros_envolvidos9: str
    cpf_cnpj_outros_envolvidos9: str
    situacao_outros_envolvidos10: str
    posicao_outros_envolvidos10: str
    nome_outros_envolvidos10: str
    cpf_cnpj_outros_envolvidos10: str