from pydantic import BaseModel


class DadosEntradaEspaiderModel(BaseModel):
    footprint:str
    url_cookie:str
    cookie_session:str
    username: str
    password: str
    fase: str
    natureza: str
    categoria: str
    tipo_acao: str
    assunto: str
    contingencia: str
    empresa: str
    unidade: str
    condicao: str
    escritorio: str
    advogado: str
    parte_contraria: str
    cpf_cnpj_parte_contraria: str
    litisconsorte: str
    orgao: str
    comarca: str
    processo: str
    data_distribuicao: str
    juizo: str
    instancia: str
    peticionamento: str
    descricao_assunto: str
    data_base_calculo: str
    data_inicio_vigencia: str
    data_inicio_contabil: str
    risco_original: str
    inestimavel: str
    moeda_indice: str
    juros: str
    desdobramento: str
    classe_partes: str
    nome_documento: str
    data_documento: str
    file: str
    parte_contraria_1: str
    cpf_cnpj_parte_processo_1: str
    condicao_parte_processo_1: str
    parte_contraria_2: str
    cpf_cnpj_parte_processo_2: str
    condicao_parte_processo_2: str
    parte_contraria_3: str
    cpf_cnpj_parte_processo_3: str
    condicao_parte_processo_3: str
    parte_contraria_4: str
    cpf_cnpj_parte_processo_4: str
    condicao_parte_processo_4: str
    parte_contraria_5: str
    cpf_cnpj_parte_processo_5: str
    condicao_parte_processo_5: str
    pedido_1: str
    valor_pedido_1: str
    pedido_2: str
    valor_pedido_2: str
    pedido_3: str
    valor_pedido_3: str
    pedido_4: str
    valor_pedido_4: str
    pedido_5: str
    valor_pedido_5: str
    pedido_6: str
    valor_pedido_6: str
    pedido_7: str
    valor_pedido_7: str
    pedido_8: str
    valor_pedido_8: str
    pedido_9: str
    valor_pedido_9: str
    pedido_10: str
    valor_pedido_10: str
    pedido_11: str
    valor_pedido_11: str
    pedido_12: str
    valor_pedido_12: str
    pedido_13: str
    valor_pedido_13: str
    pedido_14: str
    valor_pedido_14: str
    pedido_15: str
    valor_pedido_15: str
    pedido_16: str
    valor_pedido_16: str
    pedido_17: str
    valor_pedido_17: str
    pedido_18: str
    valor_pedido_18: str
    pedido_19: str
    valor_pedido_19: str
    pedido_20: str
    valor_pedido_20: str
    pedido_21: str
    valor_pedido_21: str
    pedido_22: str
    valor_pedido_22: str
    pedido_23: str
    valor_pedido_23: str
    pedido_24: str
    valor_pedido_24: str
    pedido_25: str
    valor_pedido_25: str
    pedido_26: str
    valor_pedido_26: str
    pedido_27: str
    valor_pedido_27: str
    pedido_28: str
    valor_pedido_28: str
    pedido_29: str
    valor_pedido_29: str
    pedido_30: str
    valor_pedido_30: str