from pydantic import BaseModel


class DadosEntradaEspaiderCadastroModel(BaseModel):
    footprint: str
    url_cookie: str
    cookie_session: str
    username: str
    password: str
    natureza: str
    tipo_acao: str
    cliente_principal: str
    condicao_cliente: str
    adverso_principal: str
    documento_adverso_principal: str
    condição_adverso: str
    advogado_interno_vale: str
    tipo: str
    unidade_centralizadora: str
    situacao: str
    escritorio: str
    valor_da_causa: str
    desdobramento: str
    procedimento: str
    instancia: str
    orgao: str
    juizo: str
    comarca: str
    numero_do_processo: str
    numero_processo_pre_cadastro: str
    advogado_adverso: str
    documento_advogado_adverso: str
    documento_cliente_principal: str
    tipo_audiencia: str
    modalidade: str
    alerta_prazo_audiencia: str
    vara: str
    data_andamento: str
    distribuido_em: str
    audiencia_designada: str
    hora_audiencia: str
    arquivo: str
    acao_especial: str
    unidade_controle: str
    status: str
    houve_discussao_anterior: str
    envolve_base_metais: str
    estrategico: str
    complexo: str
    mina_unidade: str
    nome_assunto: str
    tipo_documento: str
    em_andamento: str
    providencia_audiencia: str
    responsavel_audiencia: str
    status_audiencia: str
    andamento: str
